# Supported source conformance check for the one-loop retirement contract.
# The root-owned manifest names symbols and production source directories.
if(NOT DEFINED SOURCE_DIR OR NOT DEFINED MANIFEST)
    message(FATAL_ERROR "SOURCE_DIR and MANIFEST are required")
endif()
include("${MANIFEST}")
if(NOT RIGEXEC_RETIRED_SYMBOLS OR NOT RIGEXEC_RETIRED_SCAN_PATHS)
    message(FATAL_ERROR "retirement manifest must define symbols and scan paths")
endif()
foreach(_symbol IN LISTS RIGEXEC_RETIRED_SYMBOLS)
    if(NOT _symbol MATCHES "^[A-Za-z_][A-Za-z0-9_]*$")
        message(FATAL_ERROR "invalid retired C++/Python identifier: ${_symbol}")
    endif()
endforeach()
# One alternation per file. The per-symbol scan below runs only when that
# alternation hits, which is the failure path; a clean tree pays one match.
list(JOIN RIGEXEC_RETIRED_SYMBOLS "|" _joined)
set(_pattern "(^|[^A-Za-z0-9_])(${_joined})([^A-Za-z0-9_]|$)")
set(_sources)
foreach(_directory IN LISTS RIGEXEC_RETIRED_SCAN_PATHS)
    file(GLOB_RECURSE _found LIST_DIRECTORIES false
        "${SOURCE_DIR}/${_directory}/*.h" "${SOURCE_DIR}/${_directory}/*.cpp"
        "${SOURCE_DIR}/${_directory}/*.py")
    list(APPEND _sources ${_found})
endforeach()
list(REMOVE_DUPLICATES _sources)
if(NOT _sources)
    message(FATAL_ERROR "retirement manifest selected no production sources")
endif()
set(_remaining)
foreach(_file IN LISTS _sources)
    file(READ "${_file}" _text)
    if(NOT _text MATCHES "${_pattern}")
        continue()
    endif()
    foreach(_symbol IN LISTS RIGEXEC_RETIRED_SYMBOLS)
        if(_text MATCHES "(^|[^A-Za-z0-9_])${_symbol}([^A-Za-z0-9_]|$)")
            file(RELATIVE_PATH _relative "${SOURCE_DIR}" "${_file}")
            list(APPEND _remaining "${_relative}: ${_symbol}")
        endif()
    endforeach()
endforeach()
if(_remaining)
    list(JOIN _remaining "\n  " _details)
    message(FATAL_ERROR "retired one-loop symbols remain:\n  ${_details}")
endif()
list(LENGTH RIGEXEC_RETIRED_SYMBOLS _count)
message(STATUS "one-loop retirement: ${_count} symbols absent from production sources")
