# Labels for ctest -L. Called after every add_test in the root list.
# usd-free: link closure has no OpenUSD library, and the test does not
# require a fixture another test produces.
# fast: usd-free, or a test whose direct project library is only rigExecMath.
# Each directly linked project library is also a label.

set(_rigexec_pxr_libs
    arch tf gf vt sdf ts usd usdGeom usdSkel plug work exec execUsd ef vdf
    esf esfUsd hd usdImaging usdUtils hio sdr js trace pcp usdShade usdLux
    usdRender usdVol usdMedia usdPhysics cameraUtil pxOsd geomUtil glf garch hf
    usdImagingGL)
set(_rigexec_project_libs
    rigExec rigExecRuntime rigExecMath rigExecGraph rigExecBinary rigExecBake
    rigExecImaging rigExecRigging rigExecStandalone rigExecSampler rigExecLzma)
set(_rigexec_fast_direct rigExecMath)

function(_rigexec_normalize_link raw out)
    set(name "${raw}")
    if(name MATCHES "^\\$<")
        if(name MATCHES "^\\$<LINK_ONLY:(.+)>$")
            set(name "${CMAKE_MATCH_1}")
        else()
            set(${out} "" PARENT_SCOPE)
            return()
        endif()
    endif()
    if(TARGET "${name}")
        get_target_property(_alias "${name}" ALIASED_TARGET)
        if(_alias)
            set(name "${_alias}")
        endif()
    endif()
    set(${out} "${name}" PARENT_SCOPE)
endfunction()

function(_rigexec_walk_links target out_direct out_closure)
    set(_direct "")
    set(_seen "")
    set(_stack "${target}")
    set(_first TRUE)
    while(_stack)
        list(POP_FRONT _stack _cur)
        if(NOT TARGET "${_cur}")
            continue()
        endif()
        if(_cur IN_LIST _seen)
            continue()
        endif()
        list(APPEND _seen "${_cur}")
        set(_libs "")
        foreach(_prop LINK_LIBRARIES INTERFACE_LINK_LIBRARIES)
            get_target_property(_got "${_cur}" ${_prop})
            if(_got)
                list(APPEND _libs ${_got})
            endif()
        endforeach()
        foreach(_raw IN LISTS _libs)
            _rigexec_normalize_link("${_raw}" _name)
            if(NOT _name)
                continue()
            endif()
            if(_first)
                list(APPEND _direct "${_name}")
            endif()
            if(TARGET "${_name}" AND NOT _name IN_LIST _seen)
                list(APPEND _stack "${_name}")
            endif()
        endforeach()
        set(_first FALSE)
    endwhile()
    set(${out_direct} "${_direct}" PARENT_SCOPE)
    set(${out_closure} "${_seen}" PARENT_SCOPE)
endfunction()

function(rigexec_label_tests)
    get_property(_tests DIRECTORY PROPERTY TESTS)
    foreach(_test IN LISTS _tests)
        set(_cmd "")
        get_property(_cmd TEST ${_test} PROPERTY COMMAND)
        if(NOT _cmd)
            continue()
        endif()
        list(GET _cmd 0 _exe)
        get_filename_component(_exe_name "${_exe}" NAME_WE)
        set(_target "")
        if(TARGET "${_exe}")
            set(_target "${_exe}")
        elseif(TARGET "${_exe_name}")
            set(_target "${_exe_name}")
        endif()
        if(NOT _target)
            continue()
        endif()
        get_target_property(_alias "${_target}" ALIASED_TARGET)
        if(_alias)
            set(_target "${_alias}")
        endif()
        _rigexec_walk_links("${_target}" _direct _closure)
        set(_labels "")
        set(_pxr FALSE)
        foreach(_lib IN LISTS _closure)
            if(_lib IN_LIST _rigexec_pxr_libs)
                set(_pxr TRUE)
            endif()
        endforeach()
        set(_project_direct "")
        foreach(_lib IN LISTS _direct)
            if(_lib IN_LIST _rigexec_project_libs AND NOT _lib IN_LIST _labels)
                list(APPEND _labels "${_lib}")
            endif()
            if(_lib IN_LIST _rigexec_project_libs)
                list(APPEND _project_direct "${_lib}")
            endif()
        endforeach()
        set(_fixtures "")
        get_property(_fixtures TEST ${_test} PROPERTY FIXTURES_REQUIRED)
        if(NOT _pxr AND NOT _fixtures)
            list(APPEND _labels "usd-free" "fast")
        endif()
        set(_only_math TRUE)
        if(NOT _project_direct)
            set(_only_math FALSE)
        endif()
        foreach(_lib IN LISTS _project_direct)
            if(NOT _lib IN_LIST _rigexec_fast_direct)
                set(_only_math FALSE)
            endif()
        endforeach()
        if(_only_math AND NOT _fixtures AND NOT "fast" IN_LIST _labels)
            list(APPEND _labels "fast")
        endif()
        if(_labels)
            set_property(TEST ${_test} APPEND PROPERTY LABELS ${_labels})
        endif()
    endforeach()
endfunction()
